### ISSUE TITLE
Footer is not filled in

### ISSUE THREAD

**Issue by matthewdarwin** [wax-office-of-inspector-general/wax-developer#14]
**Describe the bug**

The footer says "footer content" instead of having any actual content. eg https://developer.wax.io/docs/release-notes/

![image](https://user-images.githubusercontent.com/26171839/149564820-05b82d4c-85d5-4574-a096-5a832c8a7f63.png)

**Comment by rakeden** [comment]
@matthewdarwin PR ist staged: https://github.com/wax-office-of-inspector-general/wax-developer/pull/17

**Comment by TommyFromWAX** [comment]
The Twitter link on the footer leads to Discord.

Can we please change that to https://twitter.com/WAX_io ?

![image](https://github.com/wax-office-of-inspector-general/wax-developer/assets/143025235/a3d83cec-b783-46f7-ba29-f9d3ff7ba0a6)
