### ISSUE TITLE
Edit this page on github doesn't work

### ISSUE THREAD

**Issue by matthewdarwin** [wax-office-of-inspector-general/wax-developer#15]
Edit this page on github doesn't work

For example on https://developer.wax.io/docs/release-notes/, it goes to https://github.com/wax-office-of-inspector-general/tree/main/docs/release-notes/index.md which generates a 404.

![image](https://user-images.githubusercontent.com/26171839/149564978-d13e7150-ed45-4b4b-9ab4-570fe35261ee.png)

**Comment by rakeden** [comment]
@matthewdarwin PR ist staged: https://github.com/wax-office-of-inspector-general/wax-developer/pull/17
