### ISSUE TITLE
chain.wax.io is referenced in documentation.

### ISSUE THREAD

**Issue by matthewdarwin** [wax-office-of-inspector-general/wax-developer#16]
chain.wax.io is referenced in documentation at https://developer.wax.io/docs/api-reference/rpc_api.html
This should be replaced as this is not actually usable.

![image](https://user-images.githubusercontent.com/26171839/149565091-59c7a0d7-8cfd-40b0-8f9c-d09a7a24f617.png)

**Comment by includenull** [comment]
Is anyone already planning to submit a PR for this?

I was going to but I'm not sure how best to "fix" this as it would be unfair to reference only one node.
Maybe it would be better to link to a list such as https://validate.eosnation.io/wax/reports/endpoints.html ?

**Comment by 3dkrender** [comment]
> 

Agree

**Comment by rakeden** [comment]
list of endpoints was added, thanks!
