### ISSUE TITLE
Image missing from repository

### ISSUE THREAD

**Issue by 3dkrender** [wax-office-of-inspector-general/wax-developer#181]
Attention @dapplicaio 

Part 4 of the tutorial "How to create farming game" refers to an image that does not exist in the repository:

`
/public/assets/images/tutorials/howto-create_farming_game/part4/resourcesandtokens-1024x140.png
`

This error prevents the page from being compiled.

**Comment by rakeden** [comment]
@dapplicaio I guess this is resolved through your follow-up PR #179, right?

**Comment by dapplicaio** [comment]
This is weird, as I can see that image in original merge request
 
https://github.com/wax-office-of-inspector-general/wax-developer/pull/179/commits/ddc4d07bb866f4828dbe57a6c7a9909974eef47d#diff-b86fe64522855b6532095b3af747790685b81006bd975351dff3fa27faec39d2

**Comment by rakeden** [comment]
This has been resolved and the PR has been merged. Thanks!
